all:
	mkdir -p build
	pdftex --output-directory build source/plan.tex
	pdftex --output-directory build source/Debbox_Developer_Guide.tex
	pdftex --output-directory build source/Debbox_Development_Reference.tex
clean:
	rm build -rf